public with sharing class Class1 {
    public Class1() {

        Integer testDemo = 0;
        String testString = 'String demo';
        String testString1 = 'String demo';
        String testString2 = 'String demo';
        String testString3 = 'String demo';
        String testString4 = 'String demo';
        String testString5 = 'String demo';
        String testString6 = 'String demo';

        
    }
}