public class Metro2Constants{


    public static String SEGMENT_TYPE_HEADER = 'Header';
    public static String FIELD_TYPE_ALPHA ='Alpha';
    public static String FIELD_TYPE_NUMERIC = 'Numeric';
    public static String FILED_TYPE_MONETORY = 'Monetory';
    public static String FIELD_TYPE_ALPHANUMERIC ='AlphaNumeric';
    public static String FIELD_TYPE_DATE ='Date';
    public static String SPECIAL_CHARS ='&|,|\'|@|^|/|.|#|%|!|$|^|*|(|)';
    public static String SEGMENT_TYPE_BASE = 'Base';
    public static String SEGMENT_TYPE_J1 = 'J1';
    public static String CCCD = 'Open Compliance Condition(METRO2)';
    public static String CIIC = 'Open Consumer Information(METRO2)';
    public static String SPCC = 'Open Special Condition(METRO2)';
    public static String SCB = 'Stop Credit Bureau';
}