public class PayoffConstants {
    public static String ERROR = 'ERROR';
    public static String FAIL = 'FAIL';
    public static String SYSTEM_ERROR = 'SYSTEM_ERROR';
    public static String INVALID_INPUT_FORMAT = 'INVALID_INPUT_FORMAT';
    public static String SUCCESS = 'SUCCESS';
    public static String EXCEPTON = 'EXCEPTION';
    public static String NO_ERROR = 'NO-ERROR';
    public static String ERROR_HTTP_CODE = '400';
    public static String ID_IS_NOT_PASSED = 'ID_IS_NOT_PASSED';
    public static String APP_ID_CANNOT_BE_NULL='ID_IS_NOT_PASSED';
    public static String OFFER_ERROR='MORE_THAN_ONE_OFFER_IS_SELECTED';
    public static String KEY_CANNOT_BE_NULL='KEY_CANNOT_BE_NULL';
    public static String APP_ID_INCORRECT_FORMAT='APP_ID_INCORRECT_FORMAT';
    public static String THIS_OFFER_IS_ALREADY_APPROVED='THIS_OFFER_IS_ALREADY_APPROVED';
    public static String DENIED ='DENIED';
    public static String LOAN_APPROVED = 'LOAN APPROVED';
    Public static String PRE_QUAL_COLLECTED ='pre_qual_collected';
    Public static String OFFER_ACCEPTED ='offer_accepted';
    Public static String lOAN_DETAILS_SHOWN ='loan_details_shown';
    Public static String CREDIT_SCORE_NOTICE_SHOWN ='credit_score_notice_shown';
    Public static String ACH_ACCEPTED ='ach_accepted';
    Public static String KBA_DISCLOSURE_ACCEPTED ='kba_disclosure_accepted';
    Public static String KBA_SUCCESS='kba_success';
    Public static String DCP_ACCEPTED='dcp_accepted';
    Public static String TIL_ACCEPTED='til_accepted';
    Public static String AGENT_VERIFICATION_PENDING='agent_verification_pending';
    Public static String AGENT_DOCUMENT_VERIFICATION_PENDING='agent_document_verification_pending';
    Public static String AGENT_VERIFIED='agent_verified';
    Public static String HARD_INQUIRY_DISCLOSER_ACCEPTED='hard_inquiry_disclosure_accepted';
    Public static String DOCUSIGN_LOAN_DOCS_SENT='docusign_loan_docs_sent';
    Public static String DOCUSIGN_LOAN_DOCS_COMPLETE='docusign_loan_docs_complete';
    Public static String PRE_FUNDING='pre_funding';
    Public static String FUNDED='funded';
    Public static String CREDIT_POLICY_FAILURE='credit_policy_failure';
    Public static String KBA_FAILED='kba_failed';
    Public static String HARD_INQUIRY_POST_FAILED='hard_inquiry_post_failed';
    Public static String ABANDONED_DETAILS_COLLECTED='abandoned_details_collected';
    Public static String ABANDONED_PRE_QUAL='abandoned_pre_qual';
    Public static String ABANDONED_HOUSING_PAYMENT='abandoned_housing_payment';
    Public static String ABANDONED_OFFER='abandoned_offer';
    Public static String ABANDONED_LOAN_DETAILS='abandoned_loan_details';
    Public static String ABANDONED_CREDIT_SCORE='abandoned_credit_score_notice';
    Public static String ABANDONED_ACH='abandoned_ach';
    Public static String ABANDONED_KBA='abandoned_kba';
    Public static String ABANDONED_DCP='abandoned_dcp';
    Public static String ABANDONED_TIL='abandoned_til';
    Public static String ABANDONED_HARD_INQUIRY='abandoned_hard_inquiry';
    Public static String ABANDONED_DOCSIGN ='abandoned_docusign';
    Public static String EXPIRED_OFFER ='expired_offer';
    Public static String WITHDRAWN='withdrawn';
    Public static String EXPIRED_VERIFICATION ='expired_verification';
    Public static String FRAUD ='fraud';
    Public static String REWORK_FINANCE ='rework_finance';
    Public static String DOCUSIGN_ATTACHMENT = 'docusign_attachment';


            
    
    
    
}