# Unique name for this workflow
name: Daily run test

# Definition when the workflow should run
on:
    schedule:
      # At the end of every day
      - cron: "30 10 * * *"
            
# Jobs to be executed
jobs:
    run-test-int-org:
        runs-on: ubuntu-latest
        steps:
            # Now we install nodejs in the VM, and specify version 18, below 18 might not work
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
            # Install Salesforce CLI
            - name: Setup SFDX
              uses: sfdx-actions/setup-sfdx@v1
              with:
                sfdx-auth-url: ${{ secrets.SFDX_QA_URL }}

            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: 'Run test all'
              run: |
                  mkdir testresults
                  sfdx force:apex:run:test  --target-org qa -d testresults --synchronous --test-level  RunLocalTests --wait 120 --json

            - name: Get test result
              if: ${{ always() }}
              run: |
                    TEST_ID=$(cat testresults/test-run-id.txt)
                    testsRan=$(jq .summary.testsRan testresults/test-result-${TEST_ID}.json | sed 's/"//g')
                    passing=$(jq .summary.passing testresults/test-result-${TEST_ID}.json | sed 's/"//g')
                    failing=$(jq .summary.failing testresults/test-result-${TEST_ID}.json | sed 's/"//g')
                    passRate=$(jq .summary.passRate testresults/test-result-${TEST_ID}.json | sed 's/"//g')
                    failRate=$(jq .summary.failRate testresults/test-result-${TEST_ID}.json | sed 's/"//g')
                    hostname=$(jq .summary.hostname testresults/test-result-${TEST_ID}.json | sed 's/"//g')
                    testRunCoverage=$(jq .summary.testRunCoverage testresults/test-result-${TEST_ID}.json | sed 's/"//g')
                    orgWideCoverage=$(jq .summary.orgWideCoverage testresults/test-result-${TEST_ID}.json | sed 's/"//g')

                    if [ $tetsRan!='' ]; then
                      msg="testRan : $testsRan\npassing : $passing\nfailing : $failing\npassRate : $passRate\nfailRate : $failRate\nhostname : $hostname\ntestRunCoverage : $testRunCoverage\norgWideCoverage : $orgWideCoverage"
                      echo $msg
                      echo "msg=$msg" >> $GITHUB_ENV
                    fi

            - name: Test report
              if: ${{ always() }}
              run: |
                TEST_ID=$(cat testresults/test-run-id.txt)
                sf apex get test --test-run-id ${TEST_ID}

            - name: Send custom JSON data to Slack workflow
              if: ${{ always() }}
              id: slack
              uses: slackapi/slack-github-action@v1.23.0
              with:
                payload: |
                  {
                    "text": "${{env.msg}}"
                  }
                  
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}