# This is a basic workflow to help you get started with Actions

name: Merge main to qa and e2e

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  push:
    branches: 
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #This below section can be eliminated
      - uses: actions/checkout@v2
      - name: Show Current Branch after checkout
        run: |
          echo "The Current Branch is: $(git branch --show-current)"
          git config --global user.email "gitActions@happymoney.com"
          git config --global user.name "Git Actions"
          git fetch --all
          git checkout qa
          echo "The Current Branch is (should be qa): $(git branch --show-current)"
          git merge main --allow-unrelated-histories
          git push -u origin
          git remote update
          git fetch --all
          git checkout e2e
          echo "The Current Branch is (should be e2e): $(git branch --show-current)"
          git merge main --allow-unrelated-histories
          git push -u origin
