# Unique name for this workflow
name: Deploy QA branch to QA and staging/uat orgs

# Definition when the workflow should run
on:
    push:
      branches: [ qa ]
      paths:
        - 'force-app/**'
            

# Jobs to be executed
jobs:
    deploy-branch-to-qa-org :
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:

            # Now we install nodejs in the VM, and specify version 18, below 18 might not work
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
                
            - name: Setup SFDX
              uses: sfdx-actions/setup-sfdx@v1
              with:
                sfdx-auth-url: ${{ secrets.SFDX_QA_URL }}

            # install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
            - name: 'Installing sfdx git delta'
              run: | 
                  echo y | sfdx plugins:install sfdx-git-delta
                  sfdx plugins 

            # Install java as it is required for the next step
            - name: 'Installing java'
              run: |
                sudo apt-get update
                sudo apt install default-jdk

            #JUST FOR DEMO 
            # Install jq,yq as it is required for the next step
            - name: 'Install jq,yq'
              run: |
                pip install yq
                sudo apt-get install jq

            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: 'Create delta packages for new, modified or deleted metadata'
              run: | 
                  mkdir changed-sources
                  sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/
                  echo "changed-sources"
                  if [ -d "./changed-source" ]; then
                    find changed-sources -type d -exec ls {} \;
                  fi
                  if [ -d "./destructiveChanges" ]; then
                    find destructiveChanges -type d -exec ls {} \;
                  fi

            - name: 'extract test classes in changed-sources/package/package.xml' 
              run: |
                  APEX_CLASSES=$(xq . < changed-sources/package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | map(select(. | index("*") | not)) | map(select(. | index("Test") | not)) | map(. + "Test") | unique | join(",")' -r)
                  echo $APEX_CLASSES 
                  echo "APEX_CLASSES=$APEX_CLASSES" >> $GITHUB_ENV

            # If no test specified
            - name: 'deploy delta changes - no tests'
              if: env.APEX_TESTS == 'none'
              run: |
                  if [ -d "./changed-sources/force-app" ]; then
                    #file exists
                    grep -q '<types>' changed-sources/package/package.xml && sfdx force:source:deploy -p "changed-sources/force-app"  
                  fi

            # If the env variable equals all, we run all tests
            - name: 'deploy delta changes - run all tests'
              if: env.APEX_TESTS == 'all'
              run: |
                  if [ -d "./changed-sources/force-app" ]; then
                    #file exists
                    grep -q '<types>' changed-sources/package/package.xml && sfdx force:source:deploy -p "changed-sources/force-app" -l RunLocalTests  
                  fi

            # Run tests specified by dev
            - name: 'deploy delta changes - run specified tests - User specified'
              if: env.APEX_TESTS != 'all' && env.APEX_TESTS != 'none' && env.APEX_TESTS != ''
              run: |
                  echo ${{env.APEX_TESTS}}
                  echo "--- Delta Deploy ---"
                  if [ -d "./changed-sources/force-app" ]; then
                    #file exists
                    grep -q '<types>' changed-sources/package/package.xml && sfdx force:source:deploy -p "changed-sources/force-app"  -l RunSpecifiedTests --runtests ${{env.APEX_TESTS}} 
                  fi

            # Run tests generated in change-sources/package/package.xml
            - name: 'deploy delta changes - run specified change-sources/package/package.xml'
              if: env.APEX_TESTS == '' && env.APEX_CLASSES != ''
              run: |
                  echo ${{env.APEX_TESTS}}
                  echo "--- Delta Deploy ---"
                  if [ -d "./changed-sources/force-app" ]; then
                    grep -q '<types>' changed-sources/package/package.xml && sfdx force:source:deploy -p "changed-sources/force-app"  -l RunSpecifiedTests --runtests ${{env.APEX_CLASSES}}
                  fi

            - name: 'Deploy destructive changes (if any)'
              run: |
                  sfdx force:mdapi:deploy -d "changed-sources/destructiveChanges" --ignorewarnings