on:
  push:
    branches:
      - "main"
jobs:
  merge-qa-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'qa'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
  merge-e2e-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'e2e'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
