name: Release

on:
  workflow_dispatch:



jobs:
  release:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
                with:
                  fetch-depth: 0
      - uses: actions/setup-node@v3
                with:
                  node-version: '18'
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
